# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudgov < Formula
  desc "Multi-cloud governance CLI — IAM least-privilege, cost anomalies, posture, drift, compliance, and resource hygiene across AWS, GCP, Azure, and Kubernetes"
  homepage "https://github.com/nanohype/cloudgov"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nanohype/cloudgov/releases/download/v1.0.0/cloudgov_1.0.0_darwin_amd64.tar.gz"
      sha256 "d1cd46cc4e66ee2c7107532592c279dca85c66571ac930f01ffb697ab007bf7e"

      define_method(:install) do
        bin.install "cloudgov"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nanohype/cloudgov/releases/download/v1.0.0/cloudgov_1.0.0_darwin_arm64.tar.gz"
      sha256 "4cef2ad05f9d7e99ccaf19c0bab754535172ce669b38d8a1a7c49292e581a61f"

      define_method(:install) do
        bin.install "cloudgov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nanohype/cloudgov/releases/download/v1.0.0/cloudgov_1.0.0_linux_amd64.tar.gz"
      sha256 "c5180e46fa278bccb08da2b5f256f45e0ddcd7efbb95f96ff8f5473915048a08"
      define_method(:install) do
        bin.install "cloudgov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nanohype/cloudgov/releases/download/v1.0.0/cloudgov_1.0.0_linux_arm64.tar.gz"
      sha256 "c361f0e9280d591230ceb9d420e4847d304fdcac84d69905961fe25665995597"
      define_method(:install) do
        bin.install "cloudgov"
      end
    end
  end

  test do
    system "#{bin}/cloudgov", "--version"
  end
end
