# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Matlock < Formula
  desc "Multi-cloud security and cost swiss army knife — audit IAM permissions, spot cost anomalies, find orphaned resources, and flag insecure storage across AWS, GCP, and Azure"
  homepage "https://github.com/stxkxs/matlock"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stxkxs/matlock/releases/download/v0.3.0/matlock_0.3.0_darwin_amd64.tar.gz"
      sha256 "22328b1b7ea9c34d8068ad12bbe798852455c75324b13c66c779ba908739f454"

      define_method(:install) do
        bin.install "matlock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stxkxs/matlock/releases/download/v0.3.0/matlock_0.3.0_darwin_arm64.tar.gz"
      sha256 "1c7a314ac44be1ff201d829781a33db41b3b7bc1fd4d365c19c10e893f485a3c"

      define_method(:install) do
        bin.install "matlock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stxkxs/matlock/releases/download/v0.3.0/matlock_0.3.0_linux_amd64.tar.gz"
      sha256 "8337152c101b2e2418e771976a11680f66aa14f2ebe11860234b18a8eef62295"
      define_method(:install) do
        bin.install "matlock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stxkxs/matlock/releases/download/v0.3.0/matlock_0.3.0_linux_arm64.tar.gz"
      sha256 "fcb99629825c5053522e0ff1bfbb8a681eb38e5a130476985047b37bfe153030"
      define_method(:install) do
        bin.install "matlock"
      end
    end
  end

  test do
    system "#{bin}/matlock", "--version"
  end
end
