# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Matlock < Formula
  desc "Multi-cloud security and cost swiss army knife — audit IAM permissions, spot cost anomalies, find orphaned resources, and flag insecure storage across AWS, GCP, and Azure"
  homepage "https://github.com/stxkxs/matlock"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stxkxs/matlock/releases/download/v1.0.0/matlock_1.0.0_darwin_amd64.tar.gz"
      sha256 "9e222e94dce68b16fec51ca899094cba25bdd664197271b5b1e99903d076a9a9"

      define_method(:install) do
        bin.install "matlock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stxkxs/matlock/releases/download/v1.0.0/matlock_1.0.0_darwin_arm64.tar.gz"
      sha256 "10def579723e852fe6f9c62e8b7c6358f8904a42aba82d2f30adae27d998948a"

      define_method(:install) do
        bin.install "matlock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stxkxs/matlock/releases/download/v1.0.0/matlock_1.0.0_linux_amd64.tar.gz"
      sha256 "d8a62fcc043674136a63455688b2dc80d7dfafa9d2101cbed002fa479334499a"
      define_method(:install) do
        bin.install "matlock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stxkxs/matlock/releases/download/v1.0.0/matlock_1.0.0_linux_arm64.tar.gz"
      sha256 "b98ea3c80cc049f8b086ba4f2aa3735df35bb45cdfb1b608cca8698ca2810ed8"
      define_method(:install) do
        bin.install "matlock"
      end
    end
  end

  test do
    system "#{bin}/matlock", "--version"
  end
end
